sude: required
services: 
  - docker
before_install:
  - docker build -t gorkemkarahan/docker-learning-complex-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run gorkemkarahan/docker-learning-complex-test npm test -- --coverage

after_success:
  - docker build -t gorkemkarahan/docker-learning-complex-client:latest ./client
  - docker build -t gorkemkarahan/docker-learning-complex-nginx:latest ./nginx
  - docker build -t gorkemkarahan/docker-learning-complex-server:latest ./server
  - docker build -t gorkemkarahan/docker-learning-complex-worker:latest ./worker
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # - echo docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"

  - docker push gorkemkarahan/docker-learning-complex-client:latest
  - docker push gorkemkarahan/docker-learning-complex-nginx:latest
  - docker push gorkemkarahan/docker-learning-complex-server:latest
  - docker push gorkemkarahan/docker-learning-complex-worker:latest

  depoloy:
   provider: elasticbeanstalk
   region: us-east-2
   app: Docker-Learning-Multi
   env: DockerLearningMulti-env
   bucket_name: elasticbeanstalk-us-east-2-717463034299
   bucket_path: docker-multi
   on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY