sude: required
services: 
  - docker
before_install:
  - docker build -t gorkemkarahan/docker-learning-complex-test -f ./client/Dockerfile.dev

script: 
  - docker run gorkemkarahan/docker-learning-complex-test npm test -- --coverage

after_success:
  - docker build -t gorkemkarahan/docker-learning-complex-client ./client
  - docker build -t gorkemkarahan/docker-learning-complex-nginx ./nginx
  - docker build -t gorkemkarahan/docker-learning-complex-server ./server
  - docker build -t gorkemkarahan/docker-learning-complex-worker ./worker
  
  - echo "$DOKCER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  docker push gorkemkarahan/docker-learning-complex-client
  docker push gorkemkarahan/docker-learning-complex-nginx
  docker push gorkemkarahan/docker-learning-complex-server
  docker push gorkemkarahan/docker-learning-complex-worker